Remove support for Python 3.6
jitsuin-inc/archivist-python pull request #106
Opened 2022-02-25 15:54 UTC by eccles

Problem:
Python 3.6 is EOL December 2021. Additionally we are unable
to use an increasing number of dependencies as they withdraw
support for 3.6. Subsequent work involving using swagger
json definitions to generate dataclasses is restricted to
3.7 and later.

Solution:
Remove all support for Python 3.6 and default to 3.7.

Signed-off-by: Paul Hewlett <phewlett76@gmail.com>

2022-03-02 10:21 UTC, JAG-UK requested changes

2022-03-02 10:21 UTC, JAG-UK commented on unittests/__init__.py
> +unittest.TestCase.shortDescription = lambda x: None
"verbose"?

2022-03-02 10:21 UTC, JAG-UK commented on unittests/__init__.py
> +# Hides Docstring from Verbosis mode
"verbose"?

2022-03-03 09:24 UTC, eccles commented on unittests/__init__.py
> +unittest.TestCase.shortDescription = lambda x: None
fixed

2022-03-03 09:24 UTC, eccles commented on unittests/__init__.py
> +# Hides Docstring from Verbosis mode
fixed

2022-03-22 11:26 UTC, closed without merging