Diagnostic Script for Review
jitsuin-inc/archivist-python pull request #157
Opened 2022-05-23 17:04 UTC by leflambeur

PR for the review of @CamrynCarter's diagnostic script by @eccles

2022-05-27 09:06 UTC, eccles requested changes
The code does not pass any QA - see DEVELOPMENT.md on setting up the gnecessary tools

2022-05-27 09:06 UTC, eccles commented on examples/incubator/total_counts.py
> +            id_list = list(row.keys())
id_list is not requred

2022-05-27 09:06 UTC, eccles commented on examples/incubator/total_counts.py
> +            file_name = [x.replace('/','_') for x in id_list]
`file_name = [x.replace('/','_') for x in row`

2022-05-27 09:06 UTC, eccles commented on examples/incubator/total_counts.py
> +    logging.basicConfig(filename='logfile.log',level=logging.DEBUG)
USe set_logger from the pySDK - see examples/create_asset.py

2022-05-27 18:30 UTC, CamrynCarter commented on examples/incubator/total_counts.py
> +    assets = list(arch.assets.list(props=props, attrs=attrs))
Thank you very much for reviewing the code! I appreciate your help with improvements. 

The list() function allows me to use len() for the count of assets, etc. I could use the pySDK function for counting, but it requires additional API calls and each call takes more time than len(). Also, the list type is needed for later steps, such as JSON formatting for output readability. Is there a way to use the 'generator' class similarly? The error I received is 'TypeError: Object of type generator is not JSON serializable'.

2022-05-27 18:32 UTC, CamrynCarter commented on examples/incubator/total_counts.py
> +    assets_with_location = list(arch.assets.list(props=props, attrs= attrs | {"arc_home_location_identity":"*"}))
In this case, the '|' serves to combine the two dictionaries, previously defined 'attrs' and the {"arc_home_location_identity":"*"}.

2022-05-31 21:33 UTC, CamrynCarter commented on examples/incubator/total_counts.py
> +    assets_with_location = list(arch.assets.list(props=props, attrs= attrs | {"arc_home_location_identity":"*"}))
Syntax changed to accommodate legacy versions of Python.

2022-06-06 09:46 UTC, eccles commented on examples/incubator/total_counts.py
> +    assets_with_location = list(arch.assets.list(props=props, attrs= attrs | {"arc_home_location_identity":"*"}))
ah - my misunderstanding - we only support python 3.7 for now so no features from later versions of python (3.8 onwards)

2022-06-06 09:46 UTC, eccles commented on examples/incubator/total_counts.py
> +                total_attachments.append(item['arc_attachment_identity'])
`    ...        "attributes": {
    ...            "Name": "Martin Oehl",
    ...            "arc_description": "structured attribute tests",
    ...            "info_dict": {
    ...                "id": "1234",
    ...                "sn": "5678"
    ...            },
    ...            "arc_display_name": "Structured Asset",
    ...            "arc_firmware_version": "v2",
    ...            "arc_home_location_identity": "locations/11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000",
    ...            "info_list": [
    ...                {
    ...                    "a_key": "a value",
    ...                    "other_key": "other value",
    ...                    "third_key": "val"
    ...                },
    ...                {
    ...                    "b_key": "b value",
    ...                    "another_key": "another value"
    ...                }
    ...            ]
    ...        }
`

2022-06-06 09:48 UTC, eccles commented on examples/incubator/total_counts.py
> +                total_attachments.append(item['arc_attachment_identity'])
The above is an example of how nesting may occur

2022-06-06 09:51 UTC, eccles commented on examples/incubator/total_counts.py
> +    assets = list(arch.assets.list(props=props, attrs=attrs))
the generator must be used as part of a loop in order to enumerate the list...

The len() call is only required because of the use of range...

2022-07-28 17:34 UTC, closed without merging